baseURL = "https://gemmaquinn.co.uk/"
languageCode = "en-us"
title = "Gemma Quinn"

[pagination]
  pagerSize = 10

[params]
  author = "Gemma Quinn"
  description = "Portrait artist"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true